config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1> Toutes mes magnifiques réservations !! </h1>
  <% number = 0 %>
    <% @bookings.each do |booking| %>
      Ma réservation numéro : <%=  number += 1 %>
      La voiture : <%= booking.car.brand %>
      du <%= booking.start_date %> au <%= booking.end_date %><br><br>
    <% end %>
  <h2>Vous souhaitez effectuer une autre réservation?</h2>
  <%= link_to "Voir toutes les voitures", cars_path(@cars) %>
</div>

app/views/bookings/new.html.erb
<div class="container">
    <%= simple_form_for [@car, @booking] do |f| %>
    <%= f.input :start_date, as: :date, input_html: { data: { controller: 'datepicker' } } %>
    <%= f.input :end_date, as: :date, input_html: { data: { controller: 'datepicker' } } %>
    <%= f.button :submit %>
    <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Voici votre réservation : </h1>
  <h2>Vous avez réservé du <%= @booking.start_date %> au <%= @booking.end_date %></h2>
</div>

<div class="container">
  <%= link_to "Voir Mes réservations", bookings_path(@bookings) %>
</div>

app/views/cars/index.html.erb
<div class="container">
  <h1> Voici toutes nos fantastiques voitures!!! </h1>
  <% @cars.each do |car| %>
    <%= car.brand %>
     / Prix : <%= car.price %> Simflouz
    <%= link_to "Voir la voiture", car_path(car) %><br><br>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <h1><%= @car.brand %></h1><br><br>
  Prix : <%= @car.price %> Simflouz<br><br>
  Où est-elle ? : <%= @car.address %><br><br>
  <%= link_to "La réserver maintenant!", new_car_booking_path(@car) %><br><br>
  <%= link_to "Retour", cars_path(@cars) %><br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OhMyCar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Oh my Car!</h1>
<p>Où vous trouverez les plus jolies voitures pour kiffer</p>
<%= link_to "voir nos voitures", cars_path %>
</div>